package me.shouheng.commons.config;

/**
 * Created by WngShhng on 2018/6/7.*/
public interface BaseRequestCode {
    int REQUEST_PERMISSION_STORAGE = 0x0006;
    int REQUEST_PERMISSION_PHONE_STATE = 0x0007;
    int REQUEST_PERMISSION_LOCATION = 0x0008;
    int REQUEST_PERMISSION_MICROPHONE = 0x0009;
    int REQUEST_PERMISSION_SMS = 0x000A;
    int REQUEST_PERMISSION_SENSORS = 0x000B;
    int REQUEST_PERMISSION_CONTACTS = 0x000C;
    int REQUEST_PERMISSION_CAMERA = 0x000D;
    int REQUEST_PERMISSION_CALENDAR = 0x000E;
}
